#!/bin/bash

CONFIG="$HOME/.config/wofi/big/config"
STYLE="$HOME/.config/wofi/big/style.css"

if [[ ! $(pidof wofi) ]]; then
	wofi --show drun --prompt 'Search...' --conf ${CONFIG} --style ${STYLE}
else
	pkill wofi
fi
