#!/usr/bin/env bash

# WOFI STYLES
CONFIG="$HOME/.config/wofi/big/config"
STYLE="$HOME/.config/wofi/big/style.css"

# Wofi window config (in %)
WOFI_WIDTH=28
WOFI_HEIGHT=8

wofi_command="wofi --show dmenu \
			--prompt choose... \
			--conf $CONFIG --style $STYLE \
			--width=$WOFI_WIDTH% --height=$WOFI_HEIGHT% \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--matching=fuzzy"
			
entries=$(echo -e " Poweroff\n Reboot\n Suspend\n Lock\n Logout" | $wofi_command -i --dmenu | awk '{print tolower($2)}')

case $entries in 
    poweroff|reboot|suspend)
        systemctl $entries
        ;;
    lock)
        $HOME/.config/waybar/scripts/LockScreen
        ;;
    logout)
        hyprctl dispatch exit 0
        ;;
esac
